namespace CatchUpPlatform.API.Hr.Interfaces.REST.Resources;

/// <summary>
/// Resource to create a client
/// </summary>
/// <param name="Id">The ID generated by this API</param>
/// <param name="PersonName">The person name</param>
/// <param name="Dni">The DNI</param>
/// <param name="Email">The Email</param>
/// <param name="BusinessName">The Business Name</param>
/// <param name="Phone">The Phone</param>
/// <param name="Address">The Address</param>
/// <param name="Country">The country</param>
/// <param name="City">The city</param>
/// <param name="Ruc">The ruc</param>
public record ClientResource(int Id, string PersonName, string Dni, string Email, string BusinessName, string Phone, string Address, string Country, string City, string Ruc);
