namespace CatchUpPlatform.API.News.Interfaces.REST.Resources;

/// <summary>
/// Resource for a favorite source. 
/// </summary>
/// <param name="Id">The Favorite Source ID generated by this API</param>
/// <param name="NewsApiKey">The News API Key generated by the News provider</param>
/// <param name="SourceId">The News Source ID</param>
public record FavoriteSourceResource(int Id, string NewsApiKey, string SourceId);